local skynet = require("skynet")
local buf = require("buffer")

skynet.start(function()
	local b = buf.new()
	b:PutByte(1)
	b:PutShort(0x1409)
	b:PutInt(100)
	b:PutLong(100)
	b:PutFloat(1.0)
	b:PutDouble(1.523)
	b:PutString("Hello")
	print("Buffer Content: \n" .. b:ToString())
	b:Seek(0)
	print("GetByte" .. b:GetByte())
	print("GetShort" .. b:GetShort())
	print("GetInt" .. b:GetInt())
	print("GetLong" .. b:GetLong())
	print("GetFloat" .. b:GetFloat())
	print("GetDouble " .. b:GetDouble())
	print("GetString" .. b:GetString())
end)
